name: eleventy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - run: echo "LAST_COMMIT=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npx wrangler pages deploy dist --project-name=$CF_PROJECT_NAME --branch=$GITHUB_REF_NAME
        env:
          CLOUDFLARE_API_TOKEN: ${{ vars.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          CF_PROJECT_NAME: ${{ vars.CF_PROJECT_NAME }}
