name: eleventy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@master
      - run: echo "LAST_COMMIT=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Build
        uses: cjerrington/actions-eleventy@master
      - run: mkdir -p dist/changelog
      - name: Build Changelog
        uses: withastro/action@v3
        with:
          path: ./changelog
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=${{ vars.CF_PROJECT_NAME }} --commit-dirty=true
