name: eleventy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@master
      - run: echo "LAST_COMMIT=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Build
        uses: cjerrington/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          projectName: ${{ vars.CF_PROJECT_NAME }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          directory: dist
          branch: main
